### PR TITLE
Update getFileBlock

### LINKED ISSUE #38: %zu not supported by newlib printf Arduino_STM32 toolchain
### Subject of the issue
Describe your issue here.

### Your workbench
* What platform are you using?
* What version of the device are you using? Is there a firmware version?
* How is the device wired to your platform?
* How is everything being powered?
* Are there any additional details that may help us help you?

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue to a gist.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### PR DESCRIPTION
**Pull request by fronders**
This addresses several things:

- fix #38 by changing the format string to use `%lu` specifier which will work for everyone
- add more error checking and command formatting to make `getFileBlock()` similar to other methods
- make more reliable detection of `comma_idx` - the offset of file size in `+URDBLOCK` response

### CODE REVIEW

**Comment by PaulZC** [comment]
Hi @fronders ,

Thanks for submitting this.

Some compilers are 'fussy' and will throw an error on ```%lu``` if the type isn't 'long'. I'll run the compile-sketch test on it...

Cheers,
Paul

**Comment by PaulZC** [comment]
Yeah... ```%lu``` fails on ESP32:


image


It's messy, but you can fix this with a selective compile. Something like:

```
#ifdef ARDUINO_ARCH_ESP32 // ESP32 based boards
sprintf(command, "%s=\"%s\",%zu,%zu", SARA_R5_FILE_SYSTEM_READ_BLOCK, filename.c_str(), offset, requested_length);
#else
sprintf(command, "%s=\"%s\",%lu,%lu", SARA_R5_FILE_SYSTEM_READ_BLOCK, filename.c_str(), offset, requested_length);
#endif
```

**Comment by fronders** [comment]
@PaulZC I just noticed, that I forgot to add more error handling to response parser, hence the unused `err` variable. I'll get back when I have the code

**Comment by fronders** [comment]
@PaulZC I think using it with an explicit cast to `unsigned long` would be more universal than defining platform-dependant chunks:

```cpp
// OK, yet insufficient with large sizes > ULONG_MAX
printf("%lu\n", (unsigned long) some_size_t_object); 
```

or with conditional code that covers 64-bit MCU case:

```cpp
#ifdef ULLONG_MAX
  printf("%llu\n", (unsigned long long) some_size_t_object); 
#else
  printf("%lu\n", (unsigned long) some_size_t_object); 
#endif
```

Taken from [here](https://stackoverflow.com/a/45422410), what do you think?

**Comment by fronders** [comment]
@PaulZC just added that fix from code above that should work everywhere.

Also added error handling and response checks for `getFileBlock()` as it turns out it didn't have any before

**Comment by PaulZC** [comment]
Thanks @fronders ,

I'll give this another read through tomorrow, but all looks good...

Cheers,
Paul

**Comment by fronders** [comment]
hey @PaulZC, any updates? :)

**Comment by PaulZC** [comment]
Sorry @fronders - other stuff got in the way. I'll try and do this today. Please nudge me if I don't... Thanks!

**Pull request merged**
